/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as PriceHistoryRouteImport } from './routes/price-history'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivityLogRouteImport } from './routes/activity-log'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers.$supplierId'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as InvoicesCancelledRouteImport } from './routes/invoices.cancelled'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceHistoryRoute = PriceHistoryRouteImport.update({
  id: '/price-history',
  path: '/price-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogRoute = ActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/$supplierId',
  path: '/$supplierId',
  getParentRoute: () => SuppliersRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesCancelledRoute = InvoicesCancelledRouteImport.update({
  id: '/invoices/cancelled',
  path: '/invoices/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/activity-log': typeof ActivityLogRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof CashierRoute
  '/customers': typeof CustomersRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/permissions': typeof PermissionsRoute
  '/price-history': typeof PriceHistoryRoute
  '/prices': typeof PricesRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/cancelled': typeof InvoicesCancelledRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/activity-log': typeof ActivityLogRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof CashierRoute
  '/customers': typeof CustomersRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/permissions': typeof PermissionsRoute
  '/price-history': typeof PriceHistoryRoute
  '/prices': typeof PricesRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/cancelled': typeof InvoicesCancelledRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/invoices': typeof InvoicesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/activity-log': typeof ActivityLogRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof CashierRoute
  '/customers': typeof CustomersRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/permissions': typeof PermissionsRoute
  '/price-history': typeof PriceHistoryRoute
  '/prices': typeof PricesRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/cancelled': typeof InvoicesCancelledRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounts'
    | '/activity-log'
    | '/auth'
    | '/cashier'
    | '/customers'
    | '/expenses'
    | '/export'
    | '/import'
    | '/mcp'
    | '/notifications'
    | '/payment-methods'
    | '/permissions'
    | '/price-history'
    | '/prices'
    | '/purchases'
    | '/reports'
    | '/returns'
    | '/settings'
    | '/suppliers'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/invoices/cancelled'
    | '/products/$productId'
    | '/products/new'
    | '/suppliers/$supplierId'
    | '/invoices/'
    | '/products/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounts'
    | '/activity-log'
    | '/auth'
    | '/cashier'
    | '/customers'
    | '/expenses'
    | '/export'
    | '/import'
    | '/mcp'
    | '/notifications'
    | '/payment-methods'
    | '/permissions'
    | '/price-history'
    | '/prices'
    | '/purchases'
    | '/reports'
    | '/returns'
    | '/settings'
    | '/suppliers'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/invoices/cancelled'
    | '/products/$productId'
    | '/products/new'
    | '/suppliers/$supplierId'
    | '/invoices'
    | '/products'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounts'
    | '/activity-log'
    | '/auth'
    | '/cashier'
    | '/customers'
    | '/expenses'
    | '/export'
    | '/import'
    | '/mcp'
    | '/notifications'
    | '/payment-methods'
    | '/permissions'
    | '/price-history'
    | '/prices'
    | '/purchases'
    | '/reports'
    | '/returns'
    | '/settings'
    | '/suppliers'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/invoices/cancelled'
    | '/products/$productId'
    | '/products/new'
    | '/suppliers/$supplierId'
    | '/invoices/'
    | '/products/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountsRoute: typeof AccountsRoute
  ActivityLogRoute: typeof ActivityLogRoute
  AuthRoute: typeof AuthRoute
  CashierRoute: typeof CashierRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  ExpensesRoute: typeof ExpensesRoute
  ExportRoute: typeof ExportRoute
  ImportRoute: typeof ImportRoute
  McpRoute: typeof McpRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PermissionsRoute: typeof PermissionsRoute
  PriceHistoryRoute: typeof PriceHistoryRoute
  PricesRoute: typeof PricesRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  ReturnsRoute: typeof ReturnsRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  InvoicesCancelledRoute: typeof InvoicesCancelledRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-history': {
      id: '/price-history'
      path: '/price-history'
      fullPath: '/price-history'
      preLoaderRoute: typeof PriceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-log': {
      id: '/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof ActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/cancelled': {
      id: '/invoices/cancelled'
      path: '/invoices/cancelled'
      fullPath: '/invoices/cancelled'
      preLoaderRoute: typeof InvoicesCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface SuppliersRouteChildren {
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountsRoute: AccountsRoute,
  ActivityLogRoute: ActivityLogRoute,
  AuthRoute: AuthRoute,
  CashierRoute: CashierRoute,
  CustomersRoute: CustomersRouteWithChildren,
  ExpensesRoute: ExpensesRoute,
  ExportRoute: ExportRoute,
  ImportRoute: ImportRoute,
  McpRoute: McpRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PermissionsRoute: PermissionsRoute,
  PriceHistoryRoute: PriceHistoryRoute,
  PricesRoute: PricesRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  ReturnsRoute: ReturnsRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  InvoicesCancelledRoute: InvoicesCancelledRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
